interface obj {
    img: any;
    avatar: any;
    content: String;
    name: String;
    check?: boolean;
    views: String;
    time: String;
    type?: String;
    link?: String;
    register?: boolean;
    likes?: String;
    subscriber?: String;
    description?: String;
}

export const mainApi: obj[] = [
    {
        img: require('./images/img19.webp'),
        avatar: require('./images/ava19.jpg'),
        content: 'Node.js Full Course for Beginners | Complete All-in-One Tutorial | 7 Hours',
        name: 'Dave Gray',
        check: false,
        views: '499',
        time: '1 năm',
        type: 'dev',
        link: 'f2EqECiTBL8',
        subscriber: '150 N',
        likes: '13 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img8.webp'),
        avatar: require('./images/ava8.jpg'),
        content: '40 Minutes Everyday Learn English Conversations Easily Quickly - Practice English For Speaking',
        name: 'Learn English with Jessica',
        check: true,
        views: '872',
        time: '1 giờ',
        type: 'english',
        link: 's0wbxDGgnjY',
        subscriber: '10,1 N',
        likes: '12 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img1.jpg'),
        avatar: require('./images/ava1.jpg'),
        content: 'CHẠY NGAY ĐI | RUN NOW | SƠN TÙNG M-TP | Official Music Video',
        name: 'Sơn Tùng M-TP Official',
        check: true,
        views: '153',
        time: '4 năm ',
        type: 'music',
        link: '32sYGCOYJUM',
        subscriber: '10,1 Tr',
        likes: '504 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img2.jpg'),
        avatar: require('./images/ava2.jpg'),
        content: 'Lost at night.',
        name: 'Miss.',
        check: false,
        views: '237',
        time: '1 tháng',
        type: 'music',
        link: '18v0li8yQKo',
        subscriber: '12,4 N',
        likes: '12 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img3.webp'),
        avatar: require('./images/ava3.jpg'),
        content: 'Anh Đã Từ Bỏ Rồi Đấy  - Nguyenn x @aric1407  | Official Music Video',
        name: 'Nguyên Trần Official',
        check: true,
        views: '29',
        time: '1 tháng',
        type: 'music',
        link: 'zDrji1Uwnh8',
        subscriber: '8 N',
        likes: '100 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img4.webp'),
        avatar: require('./images/ava4.jpg'),
        content: '哪里都是你',
        name: '队长YoungCaptain',
        check: true,
        views: '78',
        time: '4 năm',
        type: 'music',
        link: 'qvHa4ug5wwA',
        subscriber: '2,8 N',
        likes: '12 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img5.webp'),
        avatar: require('./images/ava5.jpg'),
        content: '交界 (伴奏)',
        name: '陈嘉杰 - Topic',
        check: false,
        views: '153',
        time: '4 năm ',
        type: 'music',
        link: 'RttPAbmzwyQ',
        subscriber: '8 Tr',
        likes: '100 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img6.webp'),
        avatar: require('./images/ava6.jpg'),
        content: '벤 (Ben) - 180도 (180 Degree) (Instrumental) [180˚]',
        name: 'Bugs Music Channel',
        check: false,
        views: '214',
        time: '4 năm',
        type: 'music',
        link: '8brcDxvBAgc',
        subscriber: '5 Tr',
        likes: '23 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img10.webp'),
        avatar: require('./images/ava10.jpg'),
        content: 'NEW INSANE LOOT GAMEPLAY🔥Pubg Mobile',
        name: 'MUNNO Gaming',
        check: true,
        views: '78',
        time: '1 giờ',
        type: 'games',
        link: 'DCnRzpS5LNI',
        subscriber: '1 Tr',
        likes: '12 Tr',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img9.webp'),
        avatar: require('./images/ava9.jpg'),
        content: 'Learn English Through Stories Level 3 🔥 | Graded reader | Learn English Through English Podcast',
        name: 'English 5days',
        check: true,
        views: '16',
        time: '5 tháng',
        type: 'english',
        link: 'vJCjaO2toP4',
        subscriber: '19 Tr',
        likes: '25 Tr',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img7.webp'),
        avatar: require('./images/ava7.jpg'),
        content: '벤 BEN - 180도 180 Degree Official M/V',
        name: 'GENIE MUSIC',
        check: true,
        views: '10',
        time: '4 năm',
        type: 'music',
        link: 'rDG9I9nx0QU',
        subscriber: '10,1 Tr',
        likes: '504 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img11.webp'),
        avatar: require('./images/ava11.jpg'),
        content:
            'Call of Duty: Modern Warfare II 2022 #1: SIÊU PHẨM CHIẾN TRANH BẮN SÚNG !!! Đồ hoạ đẹp NHƯ THẬT !!! của Trực Tiếp Game 5 tháng trước 1 giờ, 29 phút 444.953 lượt xem',
        name: 'Trực Tiếp Game',
        check: true,
        views: '78',
        time: '5 tháng',
        type: 'games',
        link: 'PTVQGcH2c78',
        subscriber: '1 N',
        likes: '5 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img12.webp'),
        avatar: require('./images/ava12.jpg'),
        content: 'Call of Duty Modern Warfare: Warzone Battle Royale Solo Gameplay (No Commentary)',
        name: 'Apollo432',
        check: true,
        views: '78',
        time: '3 năm',
        type: 'games',
        link: 'dKpL_h7va4w',
        subscriber: '655 N',
        likes: '124 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img13.webp'),
        avatar: require('./images/ava13.jpg'),
        content:
            'Phương pháp HỌC LẬP TRÌNH của Sơn Đặng! | Lộ trình học lập trình | Phương pháp học lập trình của F8 Official 2 năm trước 24 phút 107.241 lượt xem',
        name: 'F8 Official',
        check: true,
        views: '78',
        time: '2 năm',
        type: 'dev',
        link: 'DpvYHLUiZpc',
        subscriber: '10,1 Tr',
        likes: '504 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img14.webp'),
        avatar: require('./images/ava14.jpg'),
        content:
            'Ngày trong đời của một kỹ sư phần mềm - Góc nhìn thứ nhất - Làm việc tại Văn phòng Kahoot của Marko 1 năm trước 10 phút, 18 giây 2.465.816 lượt xem',
        name: 'Marko',
        check: false,
        views: '78',
        time: '1 năm',
        type: 'dev',
        link: 'tQG6jYy9xto',
        subscriber: '10,1 Tr',
        likes: '504 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img15.webp'),
        avatar: require('./images/ava15.jpg'),
        content: '4-HOUR STUDY WITH ME 🌇 / Sunset Meditation Calm Piano /  Pomodoro 50-10',
        name: 'StudyMD',
        check: true,
        views: '1.8',
        time: '6 tháng',
        type: 'dev',
        link: 'IdjDjxNn9ws',
        subscriber: '10,1 Tr',
        likes: '504 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img16.webp'),
        avatar: require('./images/ava16.jpg'),
        content: 'wating...',
        name: 'Miss.',
        check: false,
        views: '51',
        time: '3 tuần',
        type: 'music',
        link: 'dSplr1lq300',
        subscriber: '12,5 N',
        likes: '1,9 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img17.webp'),
        avatar: require('./images/ava17.jpg'),
        content: 'Xây dựng và deploy ứng dụng MERN APP - Học Full Stack (React+Redux, NodeJS , Express, MongoDB)',
        name: 'HoleTex',
        check: true,
        views: '65',
        time: '1 năm',
        link: 'khcjRUZCufs',
        type: 'dev',
        subscriber: '22,2 N',
        likes: '1,5 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img18.webp'),
        avatar: require('./images/ava18.jpg'),
        content: '30 Days to Improve Speaking Skills - Daily Conversation to Speak Confidently and Clearly',
        name: 'Learn English with Jessica',
        check: true,
        views: '112',
        time: '1 tháng',
        link: 'YOI0jFVBkg4',
        type: 'english',
        subscriber: '22,2 N',
        likes: '1,5 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img21.webp'),
        avatar: require('./images/ava21.jpg'),
        content: 'Here with me (slowed + reverb)',
        name: 'haveaniced3yy',
        check: true,
        views: '372 N',
        time: '1 tháng',
        link: 'srWIdRiNUPw',
        type: 'music',
        subscriber: '22,2 N',
        likes: '1,5 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img22.webp'),
        avatar: require('./images/ava22.jpg'),
        content: 'CSS Full Course for Beginners | Complete All-in-One Tutorial | 11 Hours',
        name: 'Dave Gray',
        check: true,
        views: '318 N',
        time: '8 tháng',
        link: 'n4R2E7O-Ngo',
        type: 'dev',
        subscriber: '152 N',
        likes: '9,3 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img23.webp'),
        avatar: require('./images/ava23.jpg'),
        content: ' 1000 MEN DESERT VALLEY BATTLE Mount & BLade 2 BANNERLORD',
        name: 'SergiuHellDragoonHQ',
        check: true,
        views: '318 N',
        time: '8 tháng',
        link: 'r7nzei7Xp34',
        type: 'games',
        subscriber: '1,5 Tr',
        likes: '52 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img24.webp'),
        avatar: require('./images/ava24.jpg'),
        content: 'Viking Army vs Mongols Horse Archers | Mount & Blade Bannerlord : Circle Formation',
        name: 'Sigma Freud',
        check: false,
        views: '577 N',
        time: '7 tháng',
        link: 'tjAD1wtgxy8',
        type: 'games',
        subscriber: '2,58 N',
        likes: '5,8 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img25.webp'),
        avatar: require('./images/ava25.jpg'),
        content: 'MERN Stack Full Tutorial & Project | Complete All-in-One Course | 8 Hours',
        name: 'Dave Gray',
        check: true,
        views: '192 N',
        time: '6 tháng',
        link: 'CvCiNeLnZ00',
        type: 'dev',
        subscriber: '152 N',
        likes: '6,3 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img26.webp'),
        avatar: require('./images/ava26.jpg'),
        content: 'LẠC TRÔI | OFFICIAL MUSIC VIDEO | SƠN TÙNG M-TP',
        name: 'Sơn Tùng M-TP Official',
        check: true,
        views: '318 N',
        time: '6 năm',
        link: 'Llw9Q6akRo4',
        type: 'music',
        subscriber: '10,1 Tr',
        likes: '1,7 Tr',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img28.webp'),
        avatar: require('./images/ava28.jpg'),
        content: 'Improve your Speaking and Conversational skills with me in only 5 MIN',
        name: 'English Fluency Journey',
        check: true,
        views: '21 N',
        time: '1 ngày',
        link: '7NP0tX9-cbE',
        type: 'english',
        subscriber: '1,31 Tr',
        likes: '1,7 N',
        description: 'This video is running at localhost:3000',
    },
    {
        img: require('./images/img27.webp'),
        avatar: require('./images/ava27.jpg'),
        content: 'Job Interview Conversation - ALL you Need about Interview Questions & Answers in English',
        name: 'Learn English with Jessica',
        check: true,
        views: '318 N',
        time: '3 ngày',
        link: '7NP0tX9-cbE',
        type: 'english',
        subscriber: '152 N',
        likes: '9,3 N',
        description: 'This video is running at localhost:3000',
    },
];
